---
- name: cyverse.irods-cfg
  src: https://github.com/CyVerse-Ansible/ansible-irods-cfg
  version: bb09d0dc81eaa8e985945624a5187012fa523822

- name: geerlingguy.apache
  src: geerlingguy.apache

- name: uoi-io.haproxy
  src: uoi-io.haproxy
