---
haproxy_num_threads: 1

haproxy_queue_timeout: null

haproxy_default_check_period: 10s
haproxy_default_client_hosts:
  - 0.0.0.0/0
haproxy_default_max_conn: 500

haproxy_stats_port: 8404
haproxy_stats_tls_crt: null
haproxy_stats_auth: null

haproxy_irods_port: 1247
haproxy_irods_reconn_ports: 20000-20199
haproxy_irods_host: localhost
haproxy_irods_direct_max_conn: "{{ haproxy_default_max_conn }}"
haproxy_irods_throttled_max_conn: "{{ haproxy_default_max_conn }}"
haproxy_irods_check_period: "{{ haproxy_default_check_period }}"
haproxy_irods_vip_client_hosts: []

haproxy_rsyslog_conf: /etc/rsyslog.d/haproxy.conf

haproxy_webdav_port: 80
haproxy_webdav_tls_port: 443
haproxy_webdav_hosts:
  - localhost
haproxy_webdav_check_period: "{{ haproxy_default_check_period }}"

haproxy_sftp_port: 22
haproxy_sftp_hosts:
  - localhost
haproxy_sftp_check_period: "{{ haproxy_default_check_period }}"
