---
- name: configure bisque client
  hosts: ies
  become: "{{ false if ansible_user|default('') == irods_service_account_name else true }}"
  become_user: "{{ irods_service_account_name }}"
  gather_facts: true
  tasks:
    - when: bisque_url is defined
      block:
        - name: install bisque_ops.py
          get_url:
            url: https://biodev.ece.ucsb.edu/projects/bisquik/browser/bisque/contrib/irods/bisque_ops/bisque_ops.py?format=txt
            dest: "{{ ansible_env.HOME }}/iRODS/server/bin/cmd/bisque_ops.py"
            mode: u=rx

        - name: place .bisque
          template:
            src: templates/bisque.j2
            dest: "{{ ansible_env.HOME }}/.bisque"
            mode: u=r

- name: configure iRODS
  hosts: irods
  become: "{{ false if ansible_user|default('') == irods_service_account_name else true }}"
  become_user: "{{ irods_service_account_name }}"
  vars:
    rabbitmq_host: "{{ groups['rabbitmq'][0] }}"
    rabbitmq_vhost_uri: "{{ rabbitmq_vhost | replace('/', '%2F') }}"
    dbms_host: "{{ groups['dbms'][0] }}"
    icat_host: "{{ groups['ies'][0] }}"

  roles:
    - role: cyverse.cyverse-irods-cfg
      irods_icat_host: "{{ icat_host }}"
      irods_default_number_of_transfer_threads: "{{ default_number_of_transfer_threads }}"
      irods_default_resource_name: "{{ irods_default_resource }}"
      irods_default_repl_resource_name: "{{ irods_default_repl_resource }}"
      irods_negotiation_key: "{{ negotiation_key }}"
      irods_parallel_transfer_buffer_size: "{{ parallel_transfer_buffer_size }}"
      irods_server_control_plane_key: "{{ server_control_plane_key }}"
      irods_server_port_range_start: "{{ server_port_range_start }}"
      irods_server_port_range_end: "{{ server_port_range_end }}"
      irods_zone_key: "{{ zone_key }}"
      irods_zone_user: "{{ irods_clerver_user }}"
      irods_db:
        host: "{{ dbms_host }}"
        port: "{{ dbms_port }}"
        username: "{{ dbms_username }}"
        password: "{{ dbms_password }}"
      irods_federation: "{{ ds_federation | default([]) }}"
      irods_single_threaded_resources: "{{ single_threaded_resources }}"
      irods_amqp_uri: "amqp://{{ rabbitmq_user }}:{{ rabbitmq_password }}@{{ rabbitmq_host }}:{{ rabbitmq_port }}/{{ rabbitmq_vhost_uri }}"
      irods_amqp_ephemeral: "{{ rabbitmq_ephemeral }}"
      irods_bisque_irods_host: "{{ bisque_irods_host | default(icat_host) }}"
      irods_sernec_owners: "{{ sernec_owners | default([]) }}"
      irods_sernec_writers: "{{ sernec_writers | default([]) }}"
      irods_sernec_readers: "{{ sernec_readers | default([]) }}"

- name: set minimum free space for resource
  hosts: rs
  become: "{{ false if ansible_user|default('') == irods_service_account_name else true }}"
  become_user: "{{ irods_service_account_name }}"
  gather_facts: false
  tasks:
    - name: initialize free space estimate
      with_items: "{{ irods_resources }}"
      shell: |
        if ! resc=$(iadmin lr '{{ item.name }}') || [ "$resc" = 'No rows found']
        then
          exit 1
        fi

        freeSpace=$(sed --quiet 's/free_space: //p' <<< "$resc")

        if [ -n "$freeSpace" ]
        then
          exit 0
        fi

        freeSpace=$(df --portability --block-size 1 '{{ item.vault }}' \
                      | tail -1 \
                      | awk '{ print $4 }')

        if ! iadmin modresc '{{ item.name }}' freespace "$freeSpace"
        then
          exit 1
        fi

        printf changed
      register: out
      changed_when: out.stdout == 'changed'

    - name: set context
      with_items: "{{ irods_resources }}"
      shell: |
        if ! currentContext=$(iadmin lr '{{ item.name }}' | sed --quiet 's/^resc_context: //p')
        then
          exit 1
        fi

        if [ '{{ item.context }}' = "$currentContext" ]
        then
          exit 0
        fi

        if ! iadmin modresc '{{ item.name }}' context '{{ item.context }}'
        then
          exit 1
        fi

        printf changed
      register: out
      changed_when: out.stdout == 'changed'
