---
#
# https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-3.noarch.rpm
#
# Use yum_repository to accomodate for error with Ansible yum module with rpm
# via url on python 2.6. The error is due to python ssl library used by
# Ansible being too old and does not support newer TLS.
#
- name: Add PostgreSQL yum repository via URL
  yum_repository:
    name: pgdg-centos93
    description: PostgreSQL 9.3 yum repo for CentOS 6
    baseurl: https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-6-x86_64/
    state: present


