---
- name: update free space estimate
  with_items: "{{ _irods_storage_resources }}"
  shell: |
    if ! resc=$(iadmin lr '{{ item.name }}') || [ "$resc" = 'No rows found' ]
    then
      printf 'Resource {{ item.name }} does not exist\n' >&2
      exit 1
    fi

    estFreeSpace=$(sed --quiet 's/free_space: //p' <<< "$resc")
    freeSpace=$(df --portability --block-size 1 '{{ item.vault }}' | tail -1 | awk '{ print $4 }')

    if [ "$freeSpace" = "$estFreeSpace" ]
    then
      exit 0
    fi

    if ! iadmin modresc '{{ item.name }}' freespace "$freeSpace"
    then
      exit 1
    fi

    printf changed
  register: out
  changed_when: out.stdout == 'changed'
  tags:
      # Even though this is technically idempotent, file systems are constantly
      # be changed by agents outside of this task. This means that a idempotency
      # check will likely fail, because of the file system being modified
      # between playbook runs by an external agent.
    - non_idempotent
