---
avra_base_collection: /testing/home/shared/avra

avra_manager: avra_mgr

avra_resource_hierarchy:
  name: avraRes
  type: passthru
  children:
    - name: avra

de_job_irods_user: de_job

irods_calliope_project_coll: /testing/home/shared/calliope

irods_default_repl_resource: rs_centos7
irods_resource_hierarchies:
  - name: rs_centos6
  - name: rs_centos7
irods_server_port_range_end: 20009

pire_resource_hierarchy:
  name: pireRes
  type: passthru
  children:
    - name: pire

terraref_base_collection: /testing/home/shared/terraref

terraref_manager: terraref_mgr

terraref_resource_hierarchy:
  name: terrarefRes
  type: passthru
  children:
    - name: terraref
